### ISSUE TITLE
[crash][macos] Constable movement crash in mission 2

### ISSUE THREAD

**Issue by Amlor** [dalerank/Akhenaten#165]
During the crash I was removing a portion of the road. Probably constable was trying to go to a removed road tile.
```
=================================================================
==63986==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x00016bd45d70 at pc 0x0001045ca550 bp 0x00016bd45d10 sp 0x00016bd45d08
READ of size 4 at 0x00016bd45d70 thread T0
    #0 0x1045ca54c in figure::roam_ticks(int) movement.cpp:534
    #1 0x10460eef0 in figure_constable::figure_action() figure_constable.cpp:211
    #2 0x104571154 in figure::action_perform() action.cpp:395
    #3 0x1044da424 in city_figures_t::update() city_figures.cpp:62
    #4 0x1046ca8b8 in game_t::update_impl(int) game.cpp:143
    #5 0x1046cc97c in game_t::update() game.cpp:604
    #6 0x1040bc9cc in run_and_draw() akhenaten.cpp:441
    #7 0x1040bcf38 in main_loop() akhenaten.cpp:617
    #8 0x1040bc3ec in main akhenaten.cpp:641
    #9 0x197f9c270  (<unknown module>)

Address 0x00016bd45d70 is located in stack of thread T0 at offset 80 in frame
    #0 0x1045c956c in figure::roam_ticks(int) movement.cpp:459

  This frame has 4 object(s):
    [32, 33) 'clamp_direction' (line 462)
    [48, 80) 'road_tiles' (line 483) <== Memory access at offset 80 overflows this variable
    [112, 132) 'agg.tmp'
    [176, 196) 'agg.tmp116'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow movement.cpp:534 in figure::roam_ticks(int)
Shadow bytes around the buggy address:
  0x00016bd45a80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00016bd45b00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00016bd45b80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00016bd45c00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00016bd45c80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x00016bd45d00: 00 00 00 00 f1 f1 f1 f1 01 f2 00 00 00 00[f2]f2
  0x00016bd45d80: f2 f2 00 00 04 f2 f2 f2 f2 f2 00 00 04 f3 f3 f3
  0x00016bd45e00: f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x00016bd45e80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00016bd45f00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00016bd45f80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==63986==ABORTING
```
![image](https://github.com/user-attachments/assets/e649aa12-b072-4983-88ea-3d67aacd1558)

**Comment by dalerank** [comment]
Fixed
